export const HOST = "https://d2l.ucalgary.ca";
export const LOGIN_URL = "https://d2l.ucalgary.ca/d2l/home";
export const TIMEZONE = "America/Edmonton";
export const DEFAULT_DUE_HOUR = 23;
export const DEFAULT_DUE_MINUTE = 59;
export const MAX_OUTLINE_BYTES = 15 * 1024 * 1024;
export const COURSE_TYPE_ID = 3;
export const PRODID = "-//UCalgary D2L Due Dates//EN";
export const UID_HOST = "ucalgary-d2l-due-dates";
